// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type FollowRel struct {
	FollowerID string `json:"follower_id"`
	FolloweeID string `json:"followee_id"`
}

type Group struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	Img       []byte       `json:"img"`
}

type Meigen struct {
	ID        uuid.UUID    `json:"id"`
	Meigen    string       `json:"meigen"`
	CreatedAt sql.NullTime `json:"created_at"`
	WhomID    string       `json:"whom_id"`
	GroupID   string       `json:"group_id"`
	PoetID    uuid.UUID    `json:"poet_id"`
}

type Poet struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	GroupID string    `json:"group_id"`
}

type Reaction struct {
	ID        uuid.UUID    `json:"id"`
	MeigenID  uuid.UUID    `json:"meigen_id"`
	UserID    string       `json:"user_id"`
	Reaction  int32        `json:"reaction"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Bio            sql.NullString `json:"bio"`
	Since          sql.NullTime   `json:"since"`
	Email          string         `json:"email"`
	Password       string         `json:"password"`
	DefaultGroupID string         `json:"default_group_id"`
	Private        bool           `json:"private"`
}

type UserGroupRel struct {
	UserID     string `json:"user_id"`
	GroupID    string `json:"group_id"`
	Permission int16  `json:"permission"`
}
