// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type FollowRel struct {
	FollowerID string
	FolloweeID string
}

type Group struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	Img       []byte
}

type Meigen struct {
	ID        uuid.UUID
	Meigen    string
	CreatedAt sql.NullTime
	WhomID    string
	GroupID   uuid.UUID
	PoetID    uuid.UUID
}

type Poet struct {
	ID      uuid.UUID
	Name    string
	GroupID uuid.UUID
}

type Reaction struct {
	ID        uuid.UUID
	MeigenID  uuid.UUID
	UserID    string
	Reaction  int32
	CreatedAt sql.NullTime
}

type User struct {
	ID             string
	Name           string
	Bio            sql.NullString
	Since          sql.NullTime
	Email          string
	Password       string
	DefaultGroupID uuid.UUID
	Private        bool
}

type UserGroupRel struct {
	UserID     string
	GroupID    uuid.UUID
	Permission int16
}
