// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Group struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	OwnerID   uuid.UUID
}

type Meigen struct {
	ID        uuid.UUID
	Meigen    string
	CreatedAt sql.NullTime
	WhomID    uuid.UUID
	GroupID   uuid.NullUUID
	PoetID    uuid.UUID
}

type Poet struct {
	ID   uuid.UUID
	Name string
}

type PoetGroupRel struct {
	PoetID  uuid.UUID
	GroupID uuid.UUID
}

type PoetUserRel struct {
	PoetID uuid.UUID
	UserID uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Name     string
	Bio      sql.NullString
	Since    sql.NullTime
	Email    string
	Password string
}

type UserGroupRel struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}
