// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_group_rels (user_id, group_id, permission) VALUES ($1, $2, $3)
`

type AddUserToGroupParams struct {
	UserID     string
	GroupID    uuid.UUID
	Permission int16
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.UserID, arg.GroupID, arg.Permission)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createMeigen = `-- name: CreateMeigen :one
INSERT INTO meigens (meigen, whom_id, group_id, poet_id) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateMeigenParams struct {
	Meigen  string
	WhomID  string
	GroupID uuid.UUID
	PoetID  uuid.UUID
}

func (q *Queries) CreateMeigen(ctx context.Context, arg CreateMeigenParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createMeigen,
		arg.Meigen,
		arg.WhomID,
		arg.GroupID,
		arg.PoetID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createPoet = `-- name: CreatePoet :one
INSERT INTO poets (name, group_id)
    SELECT name, group_id FROM poets
    WHERE NOT EXISTS (
        SELECT id, name, group_id FROM poets where poets.name = $1 AND poets.group_id = $2
    ) LIMIT 1 RETURNING id
`

type CreatePoetParams struct {
	Name    string
	GroupID uuid.UUID
}

func (q *Queries) CreatePoet(ctx context.Context, arg CreatePoetParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createPoet, arg.Name, arg.GroupID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password, default_group_id) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateUserParams struct {
	ID             string
	Name           string
	Email          string
	Password       string
	DefaultGroupID uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.DefaultGroupID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getDefaultGroupID = `-- name: GetDefaultGroupID :one
SELECT default_group_id FROM users WHERE id = $1
`

func (q *Queries) GetDefaultGroupID(ctx context.Context, id string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getDefaultGroupID, id)
	var default_group_id uuid.UUID
	err := row.Scan(&default_group_id)
	return default_group_id, err
}

const getGroupsParticipated = `-- name: GetGroupsParticipated :many
SELECT group_id from user_group_rels WHERE user_id = $1
`

func (q *Queries) GetGroupsParticipated(ctx context.Context, userID string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsParticipated, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var group_id uuid.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByName = `-- name: GetUserByName :one
SELECT id FROM users WHERE id = $1
`

func (q *Queries) GetUserByName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, id)
	err := row.Scan(&id)
	return id, err
}

const getUsernameByID = `-- name: GetUsernameByID :one
SELECT name FROM users WHERE id = $1
`

func (q *Queries) GetUsernameByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUsernameByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const groupEX = `-- name: GroupEX :one
SELECT count(*) FROM user_group_rels JOIN groups ON user_group_rels.group_id = groups.id WHERE user_id = $1 AND groups.name = $2
`

type GroupEXParams struct {
	UserID string
	Name   string
}

func (q *Queries) GroupEX(ctx context.Context, arg GroupEXParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, groupEX, arg.UserID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const initDefaultUG = `-- name: InitDefaultUG :exec
INSERT INTO user_group_rels (user_id, group_id, permission) VALUES ($1, $2, 0xffff)
`

type InitDefaultUGParams struct {
	UserID  string
	GroupID uuid.UUID
}

func (q *Queries) InitDefaultUG(ctx context.Context, arg InitDefaultUGParams) error {
	_, err := q.db.ExecContext(ctx, initDefaultUG, arg.UserID, arg.GroupID)
	return err
}

const login = `-- name: Login :one
SELECT id, name, bio, since, email, password, default_group_id FROM users WHERE id = $1 AND password = $2
`

type LoginParams struct {
	ID       string
	Password string
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, login, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Since,
		&i.Email,
		&i.Password,
		&i.DefaultGroupID,
	)
	return i, err
}

const userEXGroup = `-- name: UserEXGroup :one
SELECT count(*) from user_group_rels WHERE user_id = $1 AND group_id = $2
`

type UserEXGroupParams struct {
	UserID  string
	GroupID uuid.UUID
}

func (q *Queries) UserEXGroup(ctx context.Context, arg UserEXGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userEXGroup, arg.UserID, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
